<?php $quickshopHelper = $this->helper('Emthemes\QuickShop\Helper\Data'); ?>
<div id="quickshop" class="quickshop-modal">
	<div class="content-wrap">
    	<div class="qs-loading-wrap" style="text-align:center; display:none;">
        	<div class="qs-loader"><img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php echo __('Loading...') ?>"></div>
		</div>
        <div class="qs-content" style="display:none;"></div>
    </div>
</div>
<script type="text/javascript">
	var qsUrl = '';
</script>
<?php
$itemClass = $quickshopHelper->getConfig('quickshop/general/item_class');
$target = $quickshopHelper->getConfig('quickshop/general/target');
?>
<script type="text/x-magento-init">
{
	"*":{
		"Emthemes_QuickShop/js/quickshop":{
			"baseUrl": "<?php echo $quickshopHelper->getBaseUrl() ?>",
			"qsLabel": "",
			"itemClass": "<?php echo (!empty($itemClass))?$itemClass:"" ?>",
			"target": "<?php echo (!empty($target))?$target:".product-item-info"; ?>",
			"autoAddButtons":<?php echo ($quickshopHelper->getConfig('quickshop/general/auto_add_buttons')==1)?"true":"false" ?>
			}
	}
}
</script>
