<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher currency switcher-currency" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Currency') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="language-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                <span><?php echo $block->escapeHtml($currentCurrencyCode) ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown">
            <?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>

<script type="text/javascript">
      require(['jquery','dropdownDialog'],function($){
<?php if( $settingHelper->checkMobile()=='false'): ?>
           $("#switcher-currency<?php /* @escapeNotVerified */ echo $id?> .switcher-dropdown").dropdownDialog({
                  triggerEvent : "click",
			timeout: "0",
                  appendTo:"#switcher-currency<?php /* @escapeNotVerified */ echo $id?> > .options",
                  triggerTarget:"#switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>",
                  closeOnMouseLeave: false,
                  triggerClass:"active",
                  parentClass:"active",
                  autoSize: true,
                  buttons:null
           });      
<?php else: ?>
           $("#switcher-currency<?php /* @escapeNotVerified */ echo $id?> .switcher-dropdown").dropdownDialog({
                  triggerEvent : "click",
			timeout: "0",
                  appendTo:"#switcher-currency<?php /* @escapeNotVerified */ echo $id?> > .options",
                  triggerTarget:"#switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>",
                  closeOnMouseLeave: false,
                  triggerClass:"active",
                  parentClass:"active",
                  buttons:null
           });      
<?php endif; ?>
      });
    </script> 
</div>
<?php endif; ?>
