<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">    
    <address class="f-left">
		<span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
		<span>Magento Templates by <a href="http://www.emthemes.com/responsive-magento-themes.html" title="Responsive Magento Themes &amp; Responsive Magento Templates">EMThemes.com</a>
		</span>
	</address>						
</small>
