<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); ?>

<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php if($settingHelper->getConfig('general_section/layout/default_top_navigation') == 1): ?>
<nav class="navigation" role="navigation">
    <ul data-mage-init='{"emmenu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>
<?php endif; ?>
