<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php 
      $imageClass = "";
      if(preg_match('/alt/', $block->getCustomAttributes()))
            $imageClass = 'em-alt-hover';
      if(preg_match('/hover/', $block->getCustomAttributes()))
            $imageClass = 'em-alt-org';    

?>
<img class="photo image <?php echo $imageClass; ?>"
     <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
     src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
     width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
     height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>" />

