<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_quickShopHelper =  $this->helper('Emthemes\QuickShop\Helper\Data');
$_settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data');
//$_labelHelper =  $this->helper('Emthemes\ProductLabels\Helper\Data');

$_pageLayout = $_settingHelper->getPageConfig();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = $_settingHelper->getConfig('product_grid/grid_element/grid_show_desc');
        $showThumbnail = $_settingHelper->getConfig('product_grid/grid_element/grid_show_thumbnail');
        $showName = $_settingHelper->getConfig('product_grid/grid_element/grid_show_product_name');        
        $showPrice = $_settingHelper->getConfig('product_grid/grid_element/grid_show_price');
        $showReview = $_settingHelper->getConfig('product_grid/grid_element/grid_show_review');                       
        $showAddTo = $_settingHelper->getConfig('product_grid/grid_element/grid_show_addto');
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        
        $altImg = $_settingHelper->getConfig('product_grid/grid_element/grid_alt_img');            
           
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $showDescription = $_settingHelper->getConfig('product_list/list_element/list_show_desc');
        $showThumbnail = $_settingHelper->getConfig('product_list/list_element/list_show_thumbnail');
        $showName = $_settingHelper->getConfig('product_list/list_element/list_show_product_name');        
        $showPrice = $_settingHelper->getConfig('product_list/list_element/list_show_price');
        $showReview = $_settingHelper->getConfig('product_list/list_element/list_show_review');                       
        $showAddTo = $_settingHelper->getConfig('product_list/list_element/list_show_addto');
        

            $_iterator = 0;        
           
            
              
            $altImg = $_settingHelper->getConfig('product_list/list_element/list_alt_img');
            $gutterList = $_settingHelper->getConfig('product_list/list_element/list_gutter'); 

    }
      $hoverButton = $_settingHelper->getConfig('product_grid/grid_element/grid_config_hover');
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
      /* Column Count for Grid View */
          if($_settingHelper->getConfig('general_section/layout/disable_responsive') == 1){
              switch($_pageLayout){
                  case '3columns':
                      $_columnCountDesktop = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_threecolumns');
                      $_columnCountDesktopSmall = $_settingHelper->getConfig('product_grid/grid_desktop_small/grid_small_desktop_threecolumns');
                      $_columnCountTablet = $_settingHelper->getConfig('product_grid/grid_tablet/grid_tablet_threecolumns');
                      break;
                  case '1column':
                      $_columnCountDesktop = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_onecolumn');
                      $_columnCountDesktopSmall = $_settingHelper->getConfig('product_grid/grid_desktop_small/grid_small_desktop_onecolumn');
                      $_columnCountTablet = $_settingHelper->getConfig('product_grid/grid_tablet/grid_tablet_onecolumn');
                      break;
                  default:
                      $_columnCountDesktop = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_twocolumns');
                      $_columnCountDesktopSmall = $_settingHelper->getConfig('product_grid/grid_desktop_small/grid_small_desktop_twocolumns');
                      $_columnCountTablet = $_settingHelper->getConfig('product_grid/grid_tablet/grid_tablet_twocolumns');
                      break;
              }              
              $_columnCountMobile = $_settingHelper->getConfig('product_grid/grid_mobile/grid_items_mobile');
          }else{
              switch($_pageLayout){
                  case '3columns':
                      $_columnCountDesktop = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_threecolumns');
                      break;
                  case '1column':
                      $_columnCountDesktop = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_onecolumn');
                      break;
                  default:
                      $_columnCountDesktop = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_twocolumns');
                      break;
              }               
          }

?>
	
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <?php if($viewMode == 'grid'): ?>
            <div id="em-grid-mode">
        <?php endif; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                <div class="product-item-info" data-container="product-grid">
                    
			  <div class="product-shop-top">
			  	<?php //$_labelHelper->display($_product) ?>
           <ul class="productlabels_icons">
          <?php 
            $emLabel = array(
              'em_new_label' => __('new'),
              'em_hot_label' => __('hot'),
              'em_sale_label' => __('sale')
              );
            foreach ($emLabel as $code => $value) {
              if($_product->getData($code))
                echo "<li class='label ".$code."'><p>".$value."</p></li>";
            }
          ?>      
        </ul>
                    <?php // Product Image ?>
                    <?php if($showThumbnail): ?>
                    <?php 
                    $productImage = $block->getImage($_product, $image); 
                    $_wImg = $productImage->getWidth();
                    $_hImg = $productImage->getHeight();                   
                    /* set Ratio Image */
                    if($viewMode == 'grid'){
                        $_ratioImg = 1;
                        if($_settingHelper->getConfig('product_grid/grid_element/grid_image_ratio')!=0){
                            $_ratioImg = $_settingHelper->getConfig('product_grid/grid_element/grid_image_ratio');
                            if($_settingHelper->getConfig('product_grid/grid_element/grid_image_ratio')==1){
                                switch($this->helper('Emthemes\ThemeSettings\Helper\Data')->checkDevice()){
                                    case 'desktop':
                                        switch($_pageLayout){
                                            case '3columns':
                                                $_columnCount = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_threecolumns');                    
                                                break;
                                            case '1column':
                                                $_columnCount = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_onecolumn');
                                                break;
                                            default:
                                                $_columnCount = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_twocolumns'); 
                                                break;
                                        }
                                        $_winWidth = 1200;
                                        break;
                                    case 'tablet':
                                        switch($_pageLayout){
                                            case '3columns':
                                                $_columnCount = $_settingHelper->getConfig('product_grid/grid_tablet/grid_tablet_threecolumns');                    
                                                break;
                                            case '1column':
                                                $_columnCount = $_settingHelper->getConfig('product_grid/grid_tablet/grid_tablet_onecolumn');                    
                                                break;
                                            default:
                                                $_columnCount = $_settingHelper->getConfig('product_grid/grid_tablet/grid_tablet_twocolumns');                                                        $_columnCount = Mage::helper('themeframework/settings')->getProductsGrid_TabletTwocolumns(4); 
                                                break;
                                        }
                                        $_winWidth = 1024;
                                        break;
                                    case 'mobile': 
                                            $_columnCount = $_settingHelper->getConfig('product_grid/grid_mobile/grid_items_mobile');
                                        $_winWidth = 320;
                                        break;
                                }
                            }else{
                                switch($_pageLayout){
                                    case '3columns':
                                          $_columnCount = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_threecolumns');                    
                                        break;
                                    case '1column':
                                        $_columnCount = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_onecolumn');
                                        break;
                                    default:
                                          $_columnCount = $_settingHelper->getConfig('product_grid/grid_desktop/grid_desktop_twocolumns'); 
                                        break;
                                }
                                $_winWidth = 1200;                
                            } 
                            switch($_pageLayout){
                                case 3:
                                    $_columnsContent = 12;                    
                                    break;
                                case 1:
                                    $_columnsContent = 24;
                                    break;
                                default:
                                    $_columnsContent = 18; 
                                    break;
                            }
                            $_wImg = (($_columnsContent/24) * $_winWidth)/$_columnCount - 20;

                            if($_ratioImg== -1 ){
                                $_hImg = ($_wImg*$_settingHelper->getConfig('product_grid/grid_element/grid_custom_ratio_height'))/$_settingHelper->getConfig('product_grid/grid_element/grid_custom_ratio_width');
                            }else{
                                $_hImg = ($_wImg/$_ratioImg);
                            }
                        }
                        }
                        else{
                              
                            if(($_ratioImg = $_settingHelper->getConfig('product_list/list_element/list_image_ratio'))!=0){
                                  if($_ratioImg==-1){
                                      $_hImg = $_wImg/$_ratioImg;    
                                  }else{
                                      $_hImg = ($_wImg * $_settingHelper->getConfig('product_list/list_element/list_custom_ratio_width'))/$_settingHelper->getConfig('product_list/list_element/list_custom_ratio_height');
                                  }                        
                            } 
                        }
                    ?>
                    <?php
                    $imageAttributes = array();
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                    ?>                         
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                    <?php if($altImg != "none"): ?>
                            <?php 
                                $imageAttributes [] = "hover";
                                switch ($altImg){
                                case "small":                                     
                                    $altImage =  "category_page_".$viewMode;                            
                                    break;
                                case "thumbnail": 
                                    $altImage =  "category_page_".$viewMode."_thumbnail";                            
                                    break;
                                case "image": 
                                    $altImage =  "category_page_".$viewMode."_image";  
                                    break;
                                default:
                                    $altImage =  "category_page_".$viewMode;                                                            
                                    break;
                                }
                                $productAltImage = $_imagehelper->init($_product, $altImage)->resize($productImage->getWidth(),$productImage->getHeight());
                                //echo $productAltImage->toHtml(); 
                            ?>
                              <span class="product-image-container em-alt-hover"
                              style="width:<?php /* @escapeNotVerified */ echo $_wImg ?>px;">
                            <span class="product-image-wrapper"
                                   style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratioImg * 100); ?>%;">
                                <img class="product-image-photo"
                                     src="<?php /* @escapeNotVerified */ echo $productAltImage->getUrl(); ?>"
                                     width="<?php echo $_wImg ?>"
                                     height="<?php echo $_hImg ?>"
                                     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($productAltImage->getLabel(), null, true); ?>" /></span>
                        </span>
                    <?php endif; ?>
                    <?php 
                        $productImage = $_imagehelper->init($_product, $image)->resize($productImage->getWidth(),$productImage->getHeight());
                    ?>
                    <?php //$productImage = $block->getImage($_product, $image,$imageAttributes);  ?>
                        <?php //echo $productImage->toHtml(); ?>
                        <span class="product-image-container <?php echo ($altImg != "none") ? 'em-alt-org' : '' ?>"
                              style="width:<?php /* @escapeNotVerified */ echo $_wImg ?>px;">
                            <span class="product-image-wrapper"
                                   style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratioImg * 100); ?>%;">
                                <img class="product-image-photo"
                                     src="<?php /* @escapeNotVerified */ echo $productImage->getUrl(); ?>"
                                     width="<?php echo $_wImg ?>"
                                     height="<?php echo $_hImg ?>"
                                     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($productImage->getLabel(), null, true); ?>" /></span>
                        </span>
                    </a>
                    <?php endif; ?>
                    <?php if($viewMode == 'grid' && $hoverButton == 1): ?>
                        <?php if($showAddTo): ?>
    					<div class="em-element-display-hover bottom">
    						<div class="em-btn-addto">
    							<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                        </a>
                                    </div>
									<?php if($_quickShopHelper->getConfig('quickshop/general/active')): ?>
                                        <?php echo $_quickShopHelper->getQuickShopButton($_product); ?>
                                    <?php endif; ?>  
                                </div>
    						</div>	
    						
    					</div>
                          <?php endif; ?>    					
                    <?php endif; ?>
					</div>
					
                    <div class="product details product-item-details">
                        <?php if($showName): ?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php endif; ?>
                        <?php if($showReview): ?>
                              <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php endif; ?>
                        <?php if($showPrice): ?>                        
                              <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>                        
                              <?php echo $block->getProductDetailsHtml($_product); ?>
                        <?php endif; ?>
                         <?php // list mode ?>
                        <?php if($viewMode == 'list' || $hoverButton ==0): ?>
                         <?php if($showAddTo): ?>                       
                            <div class="actions">
                                <div class="em-btn-addto">
                                <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                        </a>
                                    </div>
                                </div>
								
                            </div>  
                            </div>
                            <?php endif; ?>
                        <?php endif;?>
                        <div class="product-item-inner">
                            
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                        
                       
                    </div>
                </div>
                </li>
            <?php endforeach; ?>
        </ol>
        <?php if($viewMode == 'grid'): ?>
            </div>
        <?php endif; ?>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
         <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {}
                    }
                }
          </script>
    <?php endif; ?>
      <script type="text/javascript">
            require(['jquery','equalElement','domReady!'],function($){
                  $('.product-items').equalElement({
                        target: '.product-item-details'                
                  });
            });
      </script>
      <script type="text/javascript">
            require(['jquery','domReady!'],function($){
                    if (typeof EM == 'undefined') EM = {};
                    if (typeof EM.SETTING == 'undefined') EM.SETTING = {};
                    
                    function setColumnCountGridMode(){  
                        var wWin = $(window).width();
                        var sGrid = $('#em-grid-mode'); 
                        if(EM.SETTING.DISABLE_RESPONSIVE==1){
                            var sDesktop = 'emcatalog-desktop-';
                            var sDesktopSmall = 'emcatalog-desktop-small-';
                            var sTablet = 'emcatalog-tablet-';
                            var sMobile = 'emcatalog-mobile-';
                            if(wWin>1200){
                                sGrid.removeClass().addClass(sDesktop+'<?php echo $_columnCountDesktop ?>');
                            }else{
                                if(wWin<=1200 && wWin>768){                                
                                    sGrid.removeClass().addClass(sDesktopSmall+'<?php echo $_columnCountDesktopSmall ?>');
                                }else{
                                    if(wWin<=768 && wWin>480){
                                        sGrid.removeClass().addClass(sTablet+'<?php echo $_columnCountTablet ?>');
                                    }else{
                                        sGrid.removeClass().addClass(sMobile+'<?php echo $_columnCountMobile ?>');   
                                    }                                
                                }
                            }
                        }else{
                            var sDesktop = 'emcatalog-desktop-';
                            sGrid.removeClass().addClass(sDesktop+'<?php echo $_columnCountDesktop ?>');
                        }                        
                    };                    
                    setColumnCountGridMode();
                    $(window).resize(function(){                       
                        setColumnCountGridMode();  	   
                    }); 
            });
      </script>
<?php endif; ?>

