<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<?php $settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); ?>
<div class="em-minicart">
<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: cart().summary_count --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: cart().summary_count -->
                <!-- ko text: cart().summary_count --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog">
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script type="text/javascript">
      require(['jquery','dropdownDialog','matchMedia'],function($){
       <?php if( $settingHelper->checkMobile()=='false'): ?>          
           $(".block-minicart").dropdownDialog({
                triggerEvent : "click",
                appendTo:"[data-block=minicart]",
                triggerTarget:".showcart",
                closeOnMouseLeave: false,
                closeOnEscape: false,
                triggerClass:"active",
                parentClass:"active",
                buttons:[]
           })
       <?php else: ?>
           $(".block-minicart").dropdownDialog({
                triggerEvent : "click",
                appendTo:"[data-block=minicart]",
                triggerTarget:".showcart",
                closeOnMouseLeave: false,
                closeOnEscape: false,
                triggerClass:"active",
                parentClass:"active",
                buttons:[]
           })
      <?php endif; ?>
      });
    </script>    
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }        
    }
    </script>
</div>
</div>


