<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Used in creating options for Yes|No config value selection
 *
 */
namespace Emthemes\ThemeSettings\Model\Config\Source;

class Stripes implements \Magento\Framework\Option\ArrayInterface
{
    /**
     * Options getter
     *
     * @return array
     */
    public function toOptionArray()
    {
        return [
            array('label' => '', 'value' => 'blank.gif'),
            array('label' => '10w.png', 'value' => '10w.png'),
            array('label' => '11w.png', 'value' => '11w.png'),
            array('label' => '12w.png', 'value' => '12w.png'),
            array('label' => '13w.png', 'value' => '13w.png'),
            array('label' => '14w.png', 'value' => '14w.png'),
            array('label' => '15w.png', 'value' => '15w.png'),
            array('label' => '16w.png', 'value' => '16w.png'),
            array('label' => '17w.png', 'value' => '17w.png'),
            array('label' => '18w.png', 'value' => '18w.png'),
            array('label' => '19w.png', 'value' => '19w.png'),
            array('label' => '1px.png', 'value' => '1px.png'),
            array('label' => '1w.png', 'value' => '1w.png'),
            array('label' => '20w.png', 'value' => '20w.png'),
            array('label' => '2w.png', 'value' => '2w.png'),
            array('label' => '3w.png', 'value' => '3w.png'),
            array('label' => '4w.png', 'value' => '4w.png'),
            array('label' => '5w.png', 'value' => '5w.png'),
            array('label' => '6w.png', 'value' => '6w.png'),
            array('label' => '7.png', 'value' => '7.png'),
            array('label' => '7w.png', 'value' => '7w.png'),
            array('label' => '8w.png', 'value' => '8w.png'),
            array('label' => '9.png', 'value' => '9.png'),
            array('label' => '9w.png', 'value' => '9w.png'),
            array('label' => 'arab_tile.png', 'value' => 'arab_tile.png'),
            array('label' => 'arches.png', 'value' => 'arches.png'),
            array('label' => 'az_subtle.png', 'value' => 'az_subtle.png'),
            array('label' => 'back_pattern.png', 'value' => 'back_pattern.png'),
            array('label' => 'billie_holiday.png', 'value' => 'billie_holiday.png'),
            array('label' => 'black_twill.png', 'value' => 'black_twill.png'),
            array('label' => 'blackorchid.png', 'value' => 'blackorchid.png'),
            array('label' => 'blizzard.png', 'value' => 'blizzard.png'),
            array('label' => 'body-bg-1.png', 'value' => 'body-bg-1.png'),
            array('label' => 'body-bg-2.png', 'value' => 'body-bg-2.png'),
            array('label' => 'cardboard_flat.png', 'value' => 'cardboard_flat.png'),
            array('label' => 'cartographer.png', 'value' => 'cartographer.png'),
            array('label' => 'classy_fabric.png', 'value' => 'classy_fabric.png'),
            array('label' => 'cloud.png', 'value' => 'cloud.png'),
            array('label' => 'clouds.png', 'value' => 'clouds.png'),
            array('label' => 'cream_dust.png', 'value' => 'cream_dust.png'),
            array('label' => 'creampaper.png', 'value' => 'creampaper.png'),
            array('label' => 'daimond_eyes.png', 'value' => 'daimond_eyes.png'),
            array('label' => 'dark_Tire.png', 'value' => 'dark_Tire.png'),
            array('label' => 'dark_geometric.png', 'value' => 'dark_geometric.png'),
            array('label' => 'darkdenim3.png', 'value' => 'darkdenim3.png'),
            array('label' => 'debut_dark.png', 'value' => 'debut_dark.png'),
            array('label' => 'debut_light.png', 'value' => 'debut_light.png'),
            array('label' => 'diagonal-line1.png', 'value' => 'diagonal-line1.png'),
            array('label' => 'diagonal_striped_brick.png', 'value' => 'diagonal_striped_brick.png'),
            array('label' => 'diagonales_decalees.png', 'value' => 'diagonales_decalees.png'),
            array('label' => 'diamond_upholstery.png', 'value' => 'diamond_upholstery.png'),
            array('label' => 'dirty_old_shirt.png', 'value' => 'dirty_old_shirt.png'),
            array('label' => 'dot.png', 'value' => 'dot.png'),
            array('label' => 'dust.png', 'value' => 'dust.png'),
            array('label' => 'embossed_paper.png', 'value' => 'embossed_paper.png'),
            array('label' => 'fabric_plaid.png', 'value' => 'fabric_plaid.png'),
            array('label' => 'foggy_birds.png', 'value' => 'foggy_birds.png'),
            array('label' => 'furley_bg.png', 'value' => 'furley_bg.png'),
            array('label' => 'gplaypattern.png', 'value' => 'gplaypattern.png'),
            array('label' => 'gray_jean.png', 'value' => 'gray_jean.png'),
            array('label' => 'grey.png', 'value' => 'grey.png'),
            array('label' => 'grid.png', 'value' => 'grid.png'),
            array('label' => 'grid1.png', 'value' => 'grid1.png'),
            array('label' => 'grid2.png', 'value' => 'grid2.png'),
            array('label' => 'grid_noise.png', 'value' => 'grid_noise.png'),
            array('label' => 'gridme.png', 'value' => 'gridme.png'),
            array('label' => 'hexabump.png', 'value' => 'hexabump.png'),
            array('label' => 'hexellence.png', 'value' => 'hexellence.png'),
            array('label' => 'horizontal-line1.png', 'value' => 'horizontal-line1.png'),
            array('label' => 'horizontal-line2.png', 'value' => 'horizontal-line2.png'),
            array('label' => 'irongrip.png', 'value' => 'irongrip.png'),
            array('label' => 'light_toast.png', 'value' => 'light_toast.png'),
            array('label' => 'light_wool.png', 'value' => 'light_wool.png'),
            array('label' => 'lil_fiber.png', 'value' => 'lil_fiber.png'),
            array('label' => 'linedpaper.png', 'value' => 'linedpaper.png'),
            array('label' => 'low_contrast_linen.png', 'value' => 'low_contrast_linen.png'),
            array('label' => 'nasty_fabric.png', 'value' => 'nasty_fabric.png'),
            array('label' => 'navy_blue.png', 'value' => 'navy_blue.png'),
            array('label' => 'noise_lines.png', 'value' => 'noise_lines.png'),
            array('label' => 'noisy_grid.png', 'value' => 'noisy_grid.png'),
            array('label' => 'norwegian_rose.png', 'value' => 'norwegian_rose.png'),
            array('label' => 'otis_redding.png', 'value' => 'otis_redding.png'),
            array('label' => 'pineapplecut.png', 'value' => 'pineapplecut.png'),
            array('label' => 'pinstriped_suit.png', 'value' => 'pinstriped_suit.png'),
            array('label' => 'purty_wood.png', 'value' => 'purty_wood.png'),
            array('label' => 'retina_dust.png', 'value' => 'retina_dust.png'),
            array('label' => 'retina_wood.png', 'value' => 'retina_wood.png'),
            array('label' => 'scribble_light.png', 'value' => 'scribble_light.png'),
            array('label' => 'shinedotted.png', 'value' => 'shinedotted.png'),
            array('label' => 'skelatal_weave.png', 'value' => 'skelatal_weave.png'),
            array('label' => 'snow.png', 'value' => 'snow.png'),
            array('label' => 'stacked_circles.png', 'value' => 'stacked_circles.png'),
            array('label' => 'starring.png', 'value' => 'starring.png'),
            array('label' => 'straws.png', 'value' => 'straws.png'),
            array('label' => 'stressed_linen.png', 'value' => 'stressed_linen.png'),
            array('label' => 'striped_lens.png', 'value' => 'striped_lens.png'),
            array('label' => 'subtle_surface.png', 'value' => 'subtle_surface.png'),
            array('label' => 'subtlenet2.png', 'value' => 'subtlenet2.png'),
            array('label' => 'swirl.png', 'value' => 'swirl.png'),
            array('label' => 'tasky_pattern.png', 'value' => 'tasky_pattern.png'),
            array('label' => 'tex2res3.png', 'value' => 'tex2res3.png'),
            array('label' => 'tex2res5.png', 'value' => 'tex2res5.png'),
            array('label' => 'tileable_wood_texture.png', 'value' => 'tileable_wood_texture.png'),
            array('label' => 'tiny_grid.png', 'value' => 'tiny_grid.png'),
            array('label' => 'txture.png', 'value' => 'txture.png'),
            array('label' => 'vertical-line1.png', 'value' => 'vertical-line1.png'),
            array('label' => 'vertical-line2.png', 'value' => 'vertical-line2.png'),
            array('label' => 'vertical-line3.png', 'value' => 'vertical-line3.png'),
            array('label' => 'vertical_cloth.png', 'value' => 'vertical_cloth.png'),
            array('label' => 'weave.png', 'value' => 'weave.png'),
            array('label' => 'white_bed_sheet.png', 'value' => 'white_bed_sheet.png'),
            array('label' => 'white_brick_wall.png', 'value' => 'white_brick_wall.png'),
            array('label' => 'white_leather.png', 'value' => 'white_leather.png'),
            array('label' => 'white_tiles.png', 'value' => 'white_tiles.png'),
            array('label' => 'white_wall.png', 'value' => 'white_wall.png'),
            array('label' => 'wild_oliva.png', 'value' => 'wild_oliva.png')
            ];
    }

    /**
     * Get options in "key-value" format
     *
     * @return array
     */
    public function toArray()
    {
        return [
             '' => 'blank.gif',
             '10w.png' => '10w.png',
             '11w.png' => '11w.png',
             '12w.png' => '12w.png',
             '13w.png' => '13w.png',
             '14w.png' => '14w.png',
             '15w.png' => '15w.png',
             '16w.png' => '16w.png',
             '17w.png' => '17w.png',
             '18w.png' => '18w.png',
             '19w.png' => '19w.png',
             '1px.png' => '1px.png',
             '1w.png' => '1w.png',
             '20w.png' => '20w.png',
             '2w.png' => '2w.png',
             '3w.png' => '3w.png',
             '4w.png' => '4w.png',
             '5w.png' => '5w.png',
             '6w.png' => '6w.png',
             '7.png' => '7.png',
             '7w.png' => '7w.png',
             '8w.png' => '8w.png',
             '9.png' => '9.png',
             '9w.png' => '9w.png',
             'arab_tile.png' => 'arab_tile.png',
             'arches.png' => 'arches.png',
             'az_subtle.png' => 'az_subtle.png',
             'back_pattern.png' => 'back_pattern.png',
             'billie_holiday.png' => 'billie_holiday.png',
             'black_twill.png' => 'black_twill.png',
             'blackorchid.png' => 'blackorchid.png',
             'blizzard.png' => 'blizzard.png',
             'body-bg-1.png' => 'body-bg-1.png',
             'body-bg-2.png' => 'body-bg-2.png',
             'cardboard_flat.png' => 'cardboard_flat.png',
             'cartographer.png' => 'cartographer.png',
             'classy_fabric.png' => 'classy_fabric.png',
             'cloud.png' => 'cloud.png',
             'clouds.png' => 'clouds.png',
             'cream_dust.png' => 'cream_dust.png',
             'creampaper.png' => 'creampaper.png',
             'daimond_eyes.png' => 'daimond_eyes.png',
             'dark_Tire.png' => 'dark_Tire.png',
             'dark_geometric.png' => 'dark_geometric.png',
             'darkdenim3.png' => 'darkdenim3.png',
             'debut_dark.png' => 'debut_dark.png',
             'debut_light.png' => 'debut_light.png',
             'diagonal-line1.png' => 'diagonal-line1.png',
             'diagonal_striped_brick.png' => 'diagonal_striped_brick.png',
             'diagonales_decalees.png' => 'diagonales_decalees.png',
             'diamond_upholstery.png' => 'diamond_upholstery.png',
             'dirty_old_shirt.png' => 'dirty_old_shirt.png',
             'dot.png' => 'dot.png',
             'dust.png' => 'dust.png',
             'embossed_paper.png' => 'embossed_paper.png',
             'fabric_plaid.png' => 'fabric_plaid.png',
             'foggy_birds.png' => 'foggy_birds.png',
             'furley_bg.png' => 'furley_bg.png',
             'gplaypattern.png' => 'gplaypattern.png',
             'gray_jean.png' => 'gray_jean.png',
             'grey.png' => 'grey.png',
             'grid.png' => 'grid.png',
             'grid1.png' => 'grid1.png',
             'grid2.png' => 'grid2.png',
             'grid_noise.png' => 'grid_noise.png',
             'gridme.png' => 'gridme.png',
             'hexabump.png' => 'hexabump.png',
             'hexellence.png' => 'hexellence.png',
             'horizontal-line1.png' => 'horizontal-line1.png',
             'horizontal-line2.png' => 'horizontal-line2.png',
             'irongrip.png' => 'irongrip.png',
             'light_toast.png' => 'light_toast.png',
             'light_wool.png' => 'light_wool.png',
             'lil_fiber.png' => 'lil_fiber.png',
             'linedpaper.png' => 'linedpaper.png',
             'low_contrast_linen.png' => 'low_contrast_linen.png',
             'nasty_fabric.png' => 'nasty_fabric.png',
             'navy_blue.png' => 'navy_blue.png',
             'noise_lines.png' => 'noise_lines.png',
             'noisy_grid.png' => 'noisy_grid.png',
             'norwegian_rose.png' => 'norwegian_rose.png',
             'otis_redding.png' => 'otis_redding.png',
             'pineapplecut.png' => 'pineapplecut.png',
             'pinstriped_suit.png' => 'pinstriped_suit.png',
             'purty_wood.png' => 'purty_wood.png',
             'retina_dust.png' => 'retina_dust.png',
             'retina_wood.png' => 'retina_wood.png',
             'scribble_light.png' => 'scribble_light.png',
             'shinedotted.png' => 'shinedotted.png',
             'skelatal_weave.png' => 'skelatal_weave.png',
             'snow.png' => 'snow.png',
             'stacked_circles.png' => 'stacked_circles.png',
             'starring.png' => 'starring.png',
             'straws.png' => 'straws.png',
             'stressed_linen.png' => 'stressed_linen.png',
             'striped_lens.png' => 'striped_lens.png',
             'subtle_surface.png' => 'subtle_surface.png',
             'subtlenet2.png' => 'subtlenet2.png',
             'swirl.png' => 'swirl.png',
             'tasky_pattern.png' => 'tasky_pattern.png',
             'tex2res3.png' => 'tex2res3.png',
             'tex2res5.png' => 'tex2res5.png',
             'tileable_wood_texture.png' => 'tileable_wood_texture.png',
             'tiny_grid.png' => 'tiny_grid.png',
             'txture.png' => 'txture.png',
             'vertical-line1.png' => 'vertical-line1.png',
             'vertical-line2.png' => 'vertical-line2.png',
             'vertical-line3.png' => 'vertical-line3.png',
             'vertical_cloth.png' => 'vertical_cloth.png',
             'weave.png' => 'weave.png',
             'white_bed_sheet.png' => 'white_bed_sheet.png',
             'white_brick_wall.png' => 'white_brick_wall.png',
             'white_leather.png' => 'white_leather.png',
             'white_tiles.png' => 'white_tiles.png',
             'white_wall.png' => 'white_wall.png',
             'wild_oliva.png' => 'wild_oliva.png'
        ];
    }
}
