<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php $settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); ?>
<?php if($settingHelper->getConfig('general_section/general_blocks/handle_login_form') == 1): ?>
<div class="block block-customer-login" style="display:none">   
        <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="dropdown-login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">                
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div> 
    <script type="text/javascript">
      require(['jquery','dropdownDialog','domReady!'],function($){
            <?php /*if( $settingHelper->checkMobile()=='false'): ?>
                       $(".block-customer-login").dropdownDialog({
                            triggerEvent : "click",          
                            appendTo:".log-in",
                            triggerTarget:".link-account",
                            closeOnMouseLeave: true,
                            triggerClass:"active",
                            parentClass:"active",
                            buttons:{}
                       });                                
            <?php endif;*/ ?>
            function effectLoginForm() {
		      var sLogin = $('.log-in .block-customer-login');
		      var sLink = $('.link-account');
		      var sDivLink = $('.log-in');  
		      if (sLogin.length > 0) {
			     <?php if( $settingHelper->checkMobile()=='false'): ?>                         
				 
					      var tmlink;
								       
					      function showlink(el) {
						      clearTimeout(tmlink);
						      tmlink = setTimeout(function() {
							      el.slideDown();
						      }, 200);
					      }    
					      function hidelink(el) {
						      clearTimeout(tmlink);
						      tmlink = setTimeout(function() {
							      el.slideUp();
						      }, 200);
					      }
					      sDivLink.mouseover(function(){
						      showlink(sLogin);
					      });
					      sDivLink.mouseout(function(){
						      hidelink(sLogin);
					      });
	                  <?php endif; ?>			    
		      }
	      }
	      effectLoginForm();
      });
    </script> 
</div>
<?php endif; ?>

