<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
<?php $settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span style="background-image: url(<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/flags/'.$block->escapeHtml($block->getCurrentStoreCode())).'.png'; ?>); background-repeat: no-repeat;"><?php echo $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown">
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                        <a style="background-image: url(<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/flags/'.$block->escapeHtml($_lang->getCode())).'.png'; ?>); background-repeat: no-repeat;" href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                            <?php echo $block->escapeHtml($_lang->getName()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>

<script type="text/javascript">
      require(['jquery','dropdownDialog'],function($){
      <?php if( $settingHelper->checkMobile()=='false'): ?>          
           $("#switcher-language<?php /* @escapeNotVerified */ echo $id?> .switcher-dropdown").dropdownDialog({
                triggerEvent : "click",
                appendTo:"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                triggerTarget:"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                closeOnMouseLeave: false,
                triggerClass:"active",
                parentClass:"active",
                buttons:null
           })
      <?php else: ?>
           $("#switcher-language<?php /* @escapeNotVerified */ echo $id?> .switcher-dropdown").dropdownDialog({
                triggerEvent : "click",
                appendTo:"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                triggerTarget:"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                closeOnMouseLeave: false,
                triggerClass:"active",
                parentClass:"active",
                buttons:null
           })
      <?php endif; ?>
      });
</script> 
</div>
<?php endif; ?>
