<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="popup-subscribe">
	<div class="em-wrapper-newsletter">
		<div class="em-block-title">
			<h2><span><?php echo __('Newsletter') ?></span></h2>
		</div>
		<p><?php echo __('Sign up to our email newsletter to be the first to hear about great offers and more') ?></p>
		<div class="em-newsletter-style05">
			<div class="block block-subscribe">
				<form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="popup-newsletter-validate-detail">
					<div class="block-content">
						<div class="form-subscribe-content">
							<div class="input-box">
							   <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
							</div>
							<div class="actions">
								<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
							</div>
						</div>
					</div>
				</form>				 
			</div>
		</div>
	</div>	
</div>
