on:
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.irievibes.be
        FTP_USERNAME: d-ftp-irie@irievibes.be
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        ARGS: --delete --exclude=shop/
        # --delete arg will delete files on the server if you've deleted them in git
