on: 
  push:
    branches:
    - Production
name: 🚀 Deploy Production on push
jobs:
  web-deploy:
    name: 🎉 Deploy Production (REAL SITE)
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.irievibes.be
        server-dir: /domains/irievibes.be/public_html/
        username: web@irievibes.be
        password: ${{ secrets.ftp_password }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/shop/**
          
        
